# Based on https://github.com/malept/rusty_blank/blob/master/.travis.yml

os:
- linux
- osx
sudo: false
dist: trusty
osx_image: xcode8.2

language: rust

rust:
  - stable
  # - beta
  # - nightly

cache: cargo

matrix:
  allow_failures:
    - rust: nightly

before_install:
- |
  rvm install "$BUILD_RUBY_VERSION"
  rvm use "$BUILD_RUBY_VERSION"
  ruby --version
  ruby -r pp -e 'pp RbConfig::CONFIG'

before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH

script:
- |
  travis-cargo build &&
  travis-cargo test

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  matrix:
    - BUILD_RUBY_VERSION: 2.3.4
      RUBY_STATIC: 1
    - BUILD_RUBY_VERSION: 2.4.1
      RUBY_STATIC: 1
